// PDF Export utilities for 12 Week Year workbook
// This generates HTML that can be converted to PDF on the client side

export interface WeeklyScoreData {
  weekNumber: number;
  executionScore: string;
  tactics: {
    title: string;
    weeklyTarget: number;
    completed: number;
  }[];
}

export interface CycleReviewData {
  cycleTitle: string;
  startDate: Date;
  endDate: Date;
  reviewType: 'mid_cycle' | 'final';
  averageExecutionScore: string;
  greatestSuccess: string;
  biggestObstacle: string;
  mostEffectiveTactic: string;
  pitfallsEncountered: string;
  adjustmentsForNextCycle: string;
  lessonsLearned: string;
  weeklyScores: { weekNumber: number; score: number }[];
  goals: { title: string; lagIndicator: string; lagTarget: string; lagCurrentValue: string }[];
}

export function generateScorecardHTML(data: WeeklyScoreData, cycleName: string): string {
  const score = parseFloat(data.executionScore);
  const scoreStatus = score >= 85 ? 'on-target' : score >= 70 ? 'below-target' : 'critical';
  const statusColor = scoreStatus === 'on-target' ? '#10b981' : scoreStatus === 'below-target' ? '#f59e0b' : '#ef4444';

  const tacticsRows = data.tactics.map(t => {
    const pct = t.weeklyTarget > 0 ? Math.min(100, (t.completed / t.weeklyTarget) * 100) : 0;
    const tactStatus = pct >= 85 ? '#10b981' : pct >= 70 ? '#f59e0b' : '#ef4444';
    return `
      <tr>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${t.title}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${t.weeklyTarget}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">${t.completed}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; text-align: center;">
          <span style="background: ${tactStatus}; color: white; padding: 4px 8px; border-radius: 4px; font-weight: 600;">
            ${pct.toFixed(0)}%
          </span>
        </td>
      </tr>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Week ${data.weekNumber} Scorecard - ${cycleName}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
          color: #1f2937;
        }
        h1 { color: #10b981; margin-bottom: 8px; }
        .subtitle { color: #6b7280; margin-bottom: 32px; }
        .score-card {
          background: linear-gradient(135deg, #10b981 0%, #059669 100%);
          color: white;
          padding: 24px;
          border-radius: 12px;
          margin-bottom: 32px;
          text-align: center;
        }
        .score-value { font-size: 48px; font-weight: 700; }
        .score-label { opacity: 0.9; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        th { 
          background: #f3f4f6; 
          padding: 12px; 
          text-align: left; 
          font-weight: 600;
          border-bottom: 2px solid #e5e7eb;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          color: #9ca3af;
          font-size: 12px;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <h1>Week ${data.weekNumber} Scorecard</h1>
      <p class="subtitle">${cycleName}</p>
      
      <div class="score-card" style="background: linear-gradient(135deg, ${statusColor} 0%, ${statusColor}dd 100%);">
        <div class="score-label">Execution Score</div>
        <div class="score-value">${score.toFixed(0)}%</div>
        <div class="score-label">Target: 85%</div>
      </div>
      
      <h2>Tactics Performance</h2>
      <table>
        <thead>
          <tr>
            <th>Tactic</th>
            <th style="text-align: center;">Target</th>
            <th style="text-align: center;">Completed</th>
            <th style="text-align: center;">Score</th>
          </tr>
        </thead>
        <tbody>
          ${tacticsRows}
        </tbody>
      </table>
      
      <div class="footer">
        Generated by 12 Week Year Workbook • ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;
}

export function generateCycleReviewHTML(data: CycleReviewData): string {
  const avgScore = parseFloat(data.averageExecutionScore || '0');
  const reviewTitle = data.reviewType === 'mid_cycle' ? 'Mid-Cycle Review (Week 6)' : 'Final Cycle Review';
  
  const goalsSection = data.goals.map((g, i) => `
    <div style="background: #f9fafb; padding: 16px; border-radius: 8px; margin-bottom: 12px;">
      <div style="display: flex; align-items: center; gap: 12px;">
        <span style="background: #10b981; color: white; width: 28px; height: 28px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 600;">${i + 1}</span>
        <div>
          <div style="font-weight: 600;">${g.title}</div>
          <div style="color: #6b7280; font-size: 14px;">${g.lagIndicator}: ${g.lagCurrentValue || '0'} / ${g.lagTarget || 'N/A'}</div>
        </div>
      </div>
    </div>
  `).join('');

  const scoreChart = data.weeklyScores.map(s => {
    const height = Math.max(10, (s.score / 100) * 100);
    const color = s.score >= 85 ? '#10b981' : s.score >= 70 ? '#f59e0b' : '#ef4444';
    return `
      <div style="display: flex; flex-direction: column; align-items: center; gap: 4px;">
        <div style="width: 24px; height: 100px; background: #e5e7eb; border-radius: 4px; display: flex; flex-direction: column-reverse;">
          <div style="width: 100%; height: ${height}%; background: ${color}; border-radius: 4px;"></div>
        </div>
        <span style="font-size: 11px; color: #6b7280;">W${s.weekNumber}</span>
      </div>
    `;
  }).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${reviewTitle} - ${data.cycleTitle}</title>
      <style>
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px;
          color: #1f2937;
        }
        h1 { color: #10b981; margin-bottom: 8px; }
        h2 { color: #374151; margin-top: 32px; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
        .subtitle { color: #6b7280; margin-bottom: 32px; }
        .stats-grid {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 16px;
          margin-bottom: 32px;
        }
        .stat-card {
          background: #f9fafb;
          padding: 20px;
          border-radius: 12px;
          text-align: center;
        }
        .stat-value { font-size: 32px; font-weight: 700; color: #10b981; }
        .stat-label { color: #6b7280; font-size: 14px; }
        .section { margin-bottom: 24px; }
        .section-title { font-weight: 600; margin-bottom: 8px; }
        .section-content { 
          background: #f9fafb; 
          padding: 16px; 
          border-radius: 8px;
          white-space: pre-wrap;
        }
        .chart-container {
          display: flex;
          gap: 8px;
          justify-content: center;
          padding: 20px;
          background: #f9fafb;
          border-radius: 12px;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          color: #9ca3af;
          font-size: 12px;
          text-align: center;
        }
      </style>
    </head>
    <body>
      <h1>${reviewTitle}</h1>
      <p class="subtitle">${data.cycleTitle} • ${new Date(data.startDate).toLocaleDateString()} - ${new Date(data.endDate).toLocaleDateString()}</p>
      
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-value">${avgScore.toFixed(0)}%</div>
          <div class="stat-label">Average Score</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${data.weeklyScores.filter(s => s.score >= 85).length}</div>
          <div class="stat-label">Weeks On Target</div>
        </div>
        <div class="stat-card">
          <div class="stat-value">${data.goals.length}</div>
          <div class="stat-label">Goals</div>
        </div>
      </div>
      
      <h2>Weekly Score Trend</h2>
      <div class="chart-container">
        ${scoreChart}
      </div>
      
      <h2>Goals Progress</h2>
      ${goalsSection || '<p style="color: #6b7280;">No goals defined for this cycle.</p>'}
      
      <h2>Reflection</h2>
      
      ${data.greatestSuccess ? `
        <div class="section">
          <div class="section-title">Greatest Success</div>
          <div class="section-content">${data.greatestSuccess}</div>
        </div>
      ` : ''}
      
      ${data.mostEffectiveTactic ? `
        <div class="section">
          <div class="section-title">Most Effective Tactic</div>
          <div class="section-content">${data.mostEffectiveTactic}</div>
        </div>
      ` : ''}
      
      ${data.biggestObstacle ? `
        <div class="section">
          <div class="section-title">Biggest Obstacle</div>
          <div class="section-content">${data.biggestObstacle}</div>
        </div>
      ` : ''}
      
      ${data.pitfallsEncountered ? `
        <div class="section">
          <div class="section-title">Pitfalls Encountered</div>
          <div class="section-content">${data.pitfallsEncountered}</div>
        </div>
      ` : ''}
      
      ${data.adjustmentsForNextCycle ? `
        <div class="section">
          <div class="section-title">Adjustments for Next ${data.reviewType === 'mid_cycle' ? 'Half' : 'Cycle'}</div>
          <div class="section-content">${data.adjustmentsForNextCycle}</div>
        </div>
      ` : ''}
      
      ${data.lessonsLearned ? `
        <div class="section">
          <div class="section-title">Lessons Learned</div>
          <div class="section-content">${data.lessonsLearned}</div>
        </div>
      ` : ''}
      
      <div class="footer">
        Generated by 12 Week Year Workbook • ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>
  `;
}
